spring.application.name=recipe-manager

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Flyway Settings
spring.flyway.enabled=true

# KEEP BELOW COMMAND DISABLED. NOT FOR PRODUCTION
spring.flyway.clean-disabled=false